-- Database querying testing
drop table test_table;
create table test_table(
  id smallint generated by default as identity primary key,
  name text not null,
  age int
);

-- RPC testing
create or replace function test_no_parameters () returns text as $$
  select 'No parameters';
$$ language sql;

create or replace function test_no_parameters_table () returns table(foo integer, bar text, bool boolean) as $$
begin
  return query
  select 1, 'asdf', true
  union
  select 2, 'ghjk', false;
end;
$$ language plpgsql;

create or replace function test_parameters_table (a integer, b integer) returns table(sum integer, difference integer) as $$
  return query select a + b, a - b;
$$ language plpgsql;


-- Authentication testing
create or replace function get_current_role() returns text as $$
  select current_user;
$$ language sql;