package org.deustomed;

import java.io.Serializable;

public class User implements Serializable {
    private static final long serialVersionUID = 1L;
    private static int idCounter = 0; //FIXME: Ids should be generated by the database

    protected int id;
    protected String name;
    protected String surname1;
    protected String surname2;
    protected String email;
    protected String password; //FIXME: The password should not be stored in the user object

    public User(int id, String name, String surname1, String surname2, String email, String password) {
        this.id = id;
        this.name = name;
        this.surname1 = surname1;
        this.surname2 = surname2;
        this.email = email;
        this.password = password;
    }

    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSurname1() {
        return surname1;
    }

    public void setSurname1(String surname1) {
        this.surname1 = surname1;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public static void setIdCounter(int idCounter) {
        User.idCounter = idCounter;
    }

    public void setId(int id) {
        this.id = id;
    }

    public void setSurname2(String surname2) {
        this.surname2 = surname2;
    }

    public static int getIdCounter() {
        return idCounter;
    }

    public String getSurname2() {
        return surname2;
    }
}
